### ISSUE TITLE
Email sent, but not to Mailjet?

### ISSUE THREAD

**Issue by jpmurray** [TheDoctor0/laravel-mailjet-driver#2]
Hello,

I've been trying to send an email using this package. I followed the instruction in the readme, everything seems to be in order here.

Using Telescope, I can see that the mails are generated, and that there is no error. But I do not receive the email, and checking Mailjet's dashboard, there is absolutely no event registered.

What would be the steps to try and debug this, if I get not error whatsoever in my app?

**Comment by jpmurray** [comment]
So it seems the global from address is ignored? I had to manually add the `->from('address')` to my mailable for the email to be sent.

I'm going to get this open, and let you decided if it's something to be checked or not, but in my case, it's solved! ;-)

**Comment by TheDoctor0** [comment]
Hello.
If Mailjet is just your mail driver I don't think this problem is related to this package as it is used by Laravel on the very last step - to send already generated and addressed email.

My first thought in this kind of situation would be to check .env file, clear config cache and restart queues (if you use queue to send mails) as it seems that invalid/empty sender address is being used here.

If it's not the case you may try to use mailtrap.io and check if without this address override in mailable your sender address is correct and authorized on Mailgun.

**Comment by TheDoctor0** [comment]
@jpmurray, did you solved it?

**Comment by jpmurray** [comment]
Honestly, no. I thought it first worked because I implicitely gave the `from` address rather than using the global from value in config. I wanted to rollback things to see where exactly it started to work but... Now it always does.

I'm starting to think that, since my mailjet account was still faily new, everything was not properly set on their end for me, and now it is.

**Comment by TheDoctor0** [comment]
> I'm starting to think that, since my mailjet account was still faily new, everything was not properly set on their end for me, and now it is.

It sounds like a reasonable explanation.

Ok, as it works fine now, I'm closing this issue.
